services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
    tty: true
    stdin_open: true
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge